[build]
  command = "npm run build"
  publish = "build"
[build]
  command = "npm run build"
  publish = "build"

# Fallback para SPA: todas las rutas van a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
